function metrics = calculate_flapping_wing_metrics_v7
% Calculate metrics for V7 Simulink outputs.

run('init_flapping_wing_v7_params.m');

cases = {'rigid_baseline','inertia_only','inertia_flex','inertia_flex_wake'};
metrics = struct([]);

fid = fopen(fullfile(result_dir_v7, 'flapping_wing_v7_report.txt'), 'w');
fprintf(fid, 'Flapping-wing V7 Simulink performance report\n');
fprintf(fid, 'Generated at: %s\n\n', datestr(now));
fprintf(fid, 'Model: %s.slx\n', model_v7);
fprintf(fid, 'All final V7 case results are generated by sim(model_v7).\n');
fprintf(fid, 'Scope: simplified flapping-wing attitude Plant, not full CFD/FSI flight reproduction.\n\n');

baseline_rmse_norm = NaN;
for i = 1:length(cases)
    case_name = cases{i};
    data = load(fullfile(result_dir_v7, ['result_v7_' case_name '.mat']));
    t = data.t;
    x = data.x;
    F_terms = data.F_terms;

    att_deg = x(:, 1:3) * 180/pi;
    rates = x(:, 4:6);

    max_abs_att = max(max(abs(att_deg)));
    final_att = att_deg(end, :);
    rmse_att = sqrt(mean(att_deg.^2, 1));
    rmse_norm = norm(rmse_att);
    iae_att = trapz(t, sum(abs(att_deg), 2));
    rate_energy = trapz(t, sum(rates.^2, 2));
    moment_rms = sqrt(mean(F_terms(:, 7:9).^2, 1));
    sat_ratio = mean(any(abs(F_terms(:, 7:9)) >= 0.999*v6_param('M_flex_limit', 0.5), 2));

    if i == 1
        baseline_rmse_norm = max(rmse_norm, 1e-9);
        rel_change = 0;
    else
        rel_change = abs(rmse_norm - baseline_rmse_norm) / baseline_rmse_norm;
    end

    metrics(i).case_name = case_name;
    metrics(i).max_abs_att_deg = max_abs_att;
    metrics(i).final_att_deg = final_att;
    metrics(i).rmse_att_deg = rmse_att;
    metrics(i).rmse_norm = rmse_norm;
    metrics(i).rmse_relative_change_vs_baseline = rel_change;
    metrics(i).iae_att = iae_att;
    metrics(i).rate_energy = rate_energy;
    metrics(i).moment_rms = moment_rms;
    metrics(i).moment_saturation_ratio = sat_ratio;

    fprintf(fid, 'Case: %s\n', case_name);
    fprintf(fid, '  max_abs_att_deg = %.6f\n', max_abs_att);
    fprintf(fid, '  final_att_deg = [%.6f %.6f %.6f]\n', final_att(1), final_att(2), final_att(3));
    fprintf(fid, '  rmse_att_deg = [%.6f %.6f %.6f]\n', rmse_att(1), rmse_att(2), rmse_att(3));
    fprintf(fid, '  rmse_relative_change_vs_baseline = %.8g\n', rel_change);
    fprintf(fid, '  iae_att = %.6f\n', iae_att);
    fprintf(fid, '  rate_energy = %.6f\n', rate_energy);
    fprintf(fid, '  rms_flexible_moments = [%.6f %.6f %.6f]\n', moment_rms(1), moment_rms(2), moment_rms(3));
    fprintf(fid, '  moment_saturation_ratio = %.6f\n', sat_ratio);
    if sat_ratio > 0.10
        fprintf(fid, '  WARNING: Flexible moment saturation is frequent. Reduce scale or increase physical moment limit with justification.\n');
    end
    fprintf(fid, '\n');
end

eq_file = fullfile(result_dir_v7, 'v6_v7_equivalence_report.txt');
if exist(eq_file, 'file')
    fprintf(fid, 'Equivalence report summary:\n');
    fprintf(fid, '%s\n', fileread(eq_file));
end

fprintf(fid, '\nInterpretation note:\n');
fprintf(fid, 'V7 converts the V6 ode45 mechanism model into a runnable Simulink Plant and validates numerical equivalence. Results remain reduced-order mechanism simulation results.\n');
fclose(fid);

save(fullfile(result_dir_v7, 'metrics_v7.mat'), 'metrics');
end
