function data = extract_v7_case_data(case_name)
% Extract a V7 Simulink-generated case result into a uniform structure.

file_path = fullfile('simulation_results_v7', ['result_v7_' case_name '.mat']);
if ~exist(file_path, 'file')
    error('Missing V7 result file: %s', file_path);
end

S = load(file_path);
required = {'t', 'x'};
for i_req = 1:numel(required)
    if ~isfield(S, required{i_req})
        error('V7 result file %s is missing field %s.', file_path, required{i_req});
    end
end

data = struct();
data.case_name = case_name;
data.t = S.t(:);
data.x = S.x;
data.att_deg = data.x(:, 1:3) * 180 / pi;
data.rates = data.x(:, 4:6);

if isfield(S, 'F_terms')
    data.flex_terms = S.F_terms;
else
    data.flex_terms = zeros(numel(data.t), 9);
end

if isfield(S, 'M_ctrl')
    data.M_ctrl = S.M_ctrl;
else
    data.M_ctrl = zeros(numel(data.t), 3);
end

data.source = 'V7 Simulink result generated by sim(flapping_wing_attitude_plant_v7)';
end

