% run_flapping_wing_simulink_comparison_v7.m
% Run four V7 Simulink cases. Final results are generated by sim(model_v7).

clear;
clc;
close all;

run('init_flapping_wing_v7_params.m');

if ~exist(result_dir_v7, 'dir')
    mkdir(result_dir_v7);
end

if ~exist([model_v7 '.slx'], 'file')
    run('build_flapping_wing_attitude_plant_v7.m');
    run('init_flapping_wing_v7_params.m');
end

cases = {
    'rigid_baseline', 0, 0, 0;
    'inertia_only', 1, 0, 0;
    'inertia_flex', 1, 1, 0;
    'inertia_flex_wake', 1, 1, 1
    };

load_system(model_v7);
set_param(model_v7, 'StopTime', num2str(sim_stop_time_v7));
set_param(model_v7, 'Solver', 'ode45');
set_param(model_v7, 'MaxStep', num2str(sim_max_step_v7));
set_param(model_v7, 'ReturnWorkspaceOutputs', 'on');

for i = 1:size(cases, 1)
    case_name = cases{i, 1};
    enable_inertia_v7 = cases{i, 2};
    enable_flex_v7 = cases{i, 3};
    enable_wake_v7 = cases{i, 4};

    assignin('base', 'enable_inertia_v7', enable_inertia_v7);
    assignin('base', 'enable_flex_v7', enable_flex_v7);
    assignin('base', 'enable_wake_v7', enable_wake_v7);
    assignin('base', 'x0_v7', x0_v7);

    simOut = sim(model_v7);
    simout_v7 = simOut.get('simout_v7');
    [t, x, F_terms, M_ctrl] = extract_v7_simout(simout_v7);

    save(fullfile(result_dir_v7, ['result_v7_' case_name '.mat']), ...
        'simOut', 'simout_v7', 't', 'x', 'F_terms', 'M_ctrl', ...
        'case_name', 'enable_inertia_v7', 'enable_flex_v7', 'enable_wake_v7');
end

close_system(model_v7, 0);

passed = compare_v6_ode_v7_simulink;
if ~passed
    error('V6/V7 equivalence failed. Do not generate final V7 plots before fixing the model.');
end

calculate_flapping_wing_metrics_v7;
plot_flapping_wing_results_v7;
sensitivity_sweep_flapping_wing_v7;

disp('V7 Simulink flapping-wing comparison completed.');
